vvod = input()
size = len(vvod)
print("Line 1", vvod[2])
print("Line 2", vvod[size - 2])
print("Line 3", vvod[:5])
print("Line 4", vvod[:-2])
print("Line 5", vvod[0:size:2])
print("Line 6", vvod[1:size:2])
print("Line 7", vvod[::-1])
print("Line 8", vvod[::-2])
print("Line 9", size)
